import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
padding = { x = 12, y = 12 }
option_as_alt = "OnlyLeft" 

[font]
size = 16
offset = { x = 0, y = 4 }
normal = { family = "SFMono Nerd Font", style = "Regular" }
bold = { family = "SFMono Nerd Font", style = "SemiBold" }
italic = { family = "SFMono Nerd Font", style = "Italic" }
bold_italic = { family = "SFMono Nerd Font", style = "SemiBold Italic" }
