return {
	"catppuccin/nvim",
	lazy = false,
	config = function()
		local catpuccin = require("catppuccin")

		catpuccin.setup({
			custom_highlights = function(colors)
				return {
					-- Snacks
					SnacksInputTitle = { fg = colors.peach },
					SnacksInputIcon = { fg = colors.peach },
					SnacksInputBorder = { fg = colors.peach },
					SnacksPicker = { bg = colors.base },

					-- Neo Tree
					NeoTreeNormal = { link = "Normal" },
					NeoTreeNormalNC = { link = "Normal" },
					NeoTreeEndOfBuffer = { link = "EndOfBuffer" },
					NeoTreeRootName = { link = "Comment" },
					NeoTreeDirectoryIcon = { link = "Conceal" },
					NeoTreeExpander = { link = "Conceal" },
				}
			end,
			flavour = "frappe",
			color_overrides = {
				-- frappe = { -- deepseek contrast
				-- 	rosewater = "#f2d5cf",
				-- 	flamingo = "#eebebe",
				-- 	pink = "#f4b8e4",
				-- 	mauve = "#ca9ee6",
				-- 	red = "#eb6b6d", -- slightly brighter red
				-- 	maroon = "#ea999c",
				-- 	peach = "#ef9f76",
				-- 	yellow = "#e5c890",
				-- 	green = "#b0d993", -- lightened green
				-- 	teal = "#81c8be",
				-- 	sky = "#99d1db",
				-- 	sapphire = "#85c1dc",
				-- 	blue = "#8caaee",
				-- 	lavender = "#babbf1",
				-- 	text = "#d0daf9", -- lightened text
				-- 	subtext1 = "#bdc7e8", -- increased contrast
				-- 	subtext0 = "#adb5d4",
				-- 	overlay2 = "#99a1c0",
				-- 	overlay1 = "#888fa9",
				-- 	overlay0 = "#787f9a",
				-- 	surface2 = "#666d87",
				-- 	surface1 = "#555b74",
				-- 	surface0 = "#444a61", -- darker surface
				-- 	base = "#2a2d3e", -- darkened base
				-- 	mantle = "#242736",
				-- 	crust = "#1e202e",
				-- },
				-- frappe = { -- anthropic contrast
				-- 	rosewater = "#f4d8d2",
				-- 	flamingo = "#f0c1c1",
				-- 	pink = "#f6bbe7",
				-- 	mauve = "#cda1e9",
				-- 	red = "#e97f81",
				-- 	maroon = "#ec9c9f",
				-- 	peach = "#f1a279",
				-- 	yellow = "#e7cb93",
				-- 	green = "#a9d58c",
				-- 	teal = "#84ccc2",
				-- 	sky = "#9cd4df",
				-- 	sapphire = "#88c4e0",
				-- 	blue = "#8fadF1",
				-- 	lavender = "#bdbef4",
				-- 	text = "#cad4f9",
				-- 	subtext1 = "#b8c2e6",
				-- 	subtext0 = "#a7b0d1",
				-- 	overlay2 = "#949cbb",
				-- 	overlay1 = "#838ba7",
				-- 	overlay0 = "#737994",
				-- 	surface2 = "#626880",
				-- 	surface1 = "#4e5469",
				-- 	surface0 = "#3e4255",
				-- 	base = "#2c3042",
				-- 	mantle = "#252938",
				-- 	crust = "#1f2230",
				-- },
				-- frappe = { -- default
				-- 	rosewater = "#f2d5cf",
				-- 	flamingo = "#eebebe",
				-- 	pink = "#f4b8e4",
				-- 	mauve = "#ca9ee6",
				-- 	red = "#e78284",
				-- 	maroon = "#ea999c",
				-- 	peach = "#ef9f76",
				-- 	yellow = "#e5c890",
				-- 	green = "#a6d189",
				-- 	teal = "#81c8be",
				-- 	sky = "#99d1db",
				-- 	sapphire = "#85c1dc",
				-- 	blue = "#8caaee",
				-- 	lavender = "#babbf1",
				-- 	text = "#c6d0f5",
				-- 	subtext1 = "#b5bfe2",
				-- 	subtext0 = "#a5adce",
				-- 	overlay2 = "#949cbb",
				-- 	overlay1 = "#838ba7",
				-- 	overlay0 = "#737994",
				-- 	surface2 = "#626880",
				-- 	surface1 = "#51576d",
				-- 	surface0 = "#414559",
				-- 	base = "#303446",
				-- 	mantle = "#292c3c",
				-- 	crust = "#232634",
				-- },
				mocha = {
					-- rosewater = "#f5e0dc",
					-- flamingo = "#f2cdcd",
					-- pink = "#f5c2e7",
					-- mauve = "#cba6f7",
					-- red = "#f38ba8",
					-- maroon = "#eba0ac",
					-- peach = "#fab387",
					-- yellow = "#f9e2af",
					-- green = "#a6e3a1",
					-- teal = "#94e2d5",
					-- sky = "#89dceb",
					-- sapphire = "#74c7ec",
					-- blue = "#89b4fa",
					-- lavender = "#b4befe",
					-- text = "#eeeeee",
					-- subtext1 = "#bac2de",
					-- subtext0 = "#a6adc8",
					-- overlay2 = "#9399b2",
					-- overlay1 = "#7f849c",
					-- overlay0 = "#6c7086",
					-- surface2 = "#585b70",
					-- surface1 = "#45475a",
					-- surface0 = "#313244",
					-- base = "#212121",
					-- mantle = "#1c1c1c",
					-- crust = "#191919",
				},
			},
		})

		vim.cmd.colorscheme("catppuccin")
	end,
}
