console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '  󰄾 '
  foreground = 'blue'
  background = 'transparent'

[transient_prompt]
  template = '{{ .PWD }} 󰅂 '
  foreground = 'darkGray'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ if eq .HostName "relay" }}󰒍 {{ end }}'
    foreground = 'yellow'
    background = 'transparent'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ if eq .HostName "pi" }} {{ end }}'
    foreground = 'magenta'
    background = 'transparent'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = '#ffffff'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '󰅂'
    foreground = 'blue'
    background = 'transparent'
    type = 'text'
    style = 'plain'
