#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = ' {{ if .SSHSession }}󰣀 {{ end }}'
    background = 'transparent'
    foreground = 'magenta'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'white'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '󰅂'

[transient_prompt]
  foreground = 'darkGray'
  background = 'transparent'
  template = '{{ .PWD }} 󰅂 '

[secondary_prompt]
  foreground = 'blue'
  background = 'transparent'
  template = '  󰄾 '
