gui:
  showRandomTip: false
  showCommandLog: false
  showBottomLine: false
git:
  paging:
    colorArg: always
    pager: delta --paging=never --syntax-theme 'Catppuccin Frappe' --side-by-side --tabs 2
