# Status Background
set -g status-style "bg=default"

# 

# Status Left
set -g status-left-length 100
set -g status-left " "
set -ga status-left "#{?client_prefix,#[fg=#{@thm_surface1}] ,#[fg=#{@thm_surface0}] }"
set -ga status-left "#[fg=#{@thm_surface1}]#S "
set -ga status-left "#[fg=#{@thm_surface0}]│"

# Window
set -gF window-status-separator " #[fg=#{@thm_surface0}]│"
set -g window-status-style "fg=#{@thm_surface1}"
set -g window-status-format " #I.#W"
set -g window-status-current-style "fg=#{@thm_sapphire}"
set -g window-status-current-format " #I.#W"

# Status Right
set -g status-right-length 100

set -g status-right '#(
  STATUS="#[fg=#{@thm_surface1}]  #{=/-32/...:#{#{b:pane_current_path}}} ";

  if ! git -C "#{pane_current_path}" rev-parse --is-inside-work-tree &>/dev/null; then
    echo "${STATUS}#[fg=#{@thm_surface0}]│#[fg=#{@thm_surface1}] ⎇  ";
    exit 0;
  fi;

  BRANCH_NAME=$(git -C "#{pane_current_path}" rev-parse --abbrev-ref HEAD 2>/dev/null);
  BRANCH_COLOR="#[fg=#{@thm_surface1}]";

  if [ "$BRANCH_NAME" = "HEAD" ]; then
    BRANCH_COLOR="#[fg=#{@thm_peach}]";
  fi;

  if [ -d "$(git -C "#{pane_current_path}" rev-parse --git-path rebase-merge 2>/dev/null)" ] || \
     [ -d "$(git -C "#{pane_current_path}" rev-parse --git-path rebase-apply 2>/dev/null)" ]; then
    BRANCH_COLOR="#[fg=#{@thm_peach}]";
  fi;

  STATUS="${STATUS}#[fg=#{@thm_surface0}]│${BRANCH_COLOR} ⎇ ";
  BRANCH_NAME=$(git -C "#{pane_current_path}" rev-parse --abbrev-ref HEAD 2>/dev/null);
  STATUS="${STATUS}#[fg=#{@thm_surface1}]${BRANCH_NAME} "
  STATUS_SB=$(git -C "#{pane_current_path}" status -sb --porcelain 2>/dev/null);

  INDICATORS=""

  if echo "$STATUS_SB" | grep -q "ahead"; then
    INDICATORS="${INDICATORS}#[fg=#{@thm_overlay2}]↑ "
  fi;

  if echo "$STATUS_SB" | grep -q "behind"; then
    INDICATORS="${INDICATORS}#[fg=#{@thm_peach}]↓ "
  fi;

  if echo "$STATUS_SB" | grep -qE '^[MADRCU?!]'; then
    INDICATORS="${INDICATORS}#[fg=#{@thm_overlay2}]* "
  fi;

  echo "${STATUS}${INDICATORS}";
)'


# Pane
set -wgF pane-active-border-style "fg=#{@thm_surface2}"
set -wgF pane-border-style "fg=#{@thm_surface0}"

# Popups
set -gF popup-style "bg=#{@thm_base},fg=#{@thm_text}"
set -gF popup-border-style "fg=#{@thm_yellow}"

# Message
set -gF message-style "fg=#{@thm_green}"
set -gF message-command-style "fg=#{@thm_green}"

# Mode
set -gF mode-style "bg=#{@thm_surface0},bold"
