# Status Background
set -g status-style "bg=default"

# Status Left
set -g status-left-length 100
set -g status-left ""
set -ga status-left " #{?client_prefix,#[fg=#{@thm_surface2}] ,#[fg=#{@thm_surface1}] }"
set -ga status-left ""
set -ga status-left "#[fg=#{@thm_surface1}]#S #[fg=#{@thm_surface0}]│"

# Window
set -gF window-status-separator " #[fg=#{@thm_surface0}]│"
set -g window-status-format " #I#{?#{!=:#{window_name},Window},:#W,}"
set -g window-status-style "fg=#{@thm_surface1}"
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},:#W,}"
set -g window-status-current-style "fg=#{@thm_blue}"

# Status Right
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#{?#{!=:#{b:socket_path},default}, #[fg=#{@thm_surface1}] #{b:socket_path},}"
set -ga status-right "#{?#{!=:#{b:socket_path},default}, #[fg=#{@thm_surface0}]│,}"
set -ga status-right "#[fg=#{@thm_surface1}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-right "#[fg=#{@thm_surface0}]│"
set -ga status-right "#[fg=#{@thm_surface1}]  #{pane_current_command} "

# Pane
set -wgF pane-active-border-style "fg=#{@thm_surface2}"
set -wgF pane-border-style "fg=#{@thm_surface0}"

# Popups
set -gF popup-style "bg=#{@thm_base},fg=#{@thm_text}"
set -gF popup-border-style "fg=#{@thm_yellow}"

# Message
set -gF message-style "fg=#{@thm_green}"
set -gF message-command-style "fg=#{@thm_green}"

# Mode
set -gF mode-style "bg=#{@thm_surface0},bold"
