# status bg
set -g status-style "bg=default"

# status left
set -g status-left-length 100
set -g status-left ""
set -ga status-left "#{?#{!=:#{b:socket_path},default},  #{b:socket_path},}"
set -ga status-left "#{?#{!=:#{b:socket_path},default}, #[fg=brightblack]│,}"
set -ga status-left " #{?client_prefix,#[fg=white] ,#[fg=brightblack] }"
set -ga status-left ""
# set -ga status-left "#{?client_prefix,#{#[fg=#{@thm_subtle}]#S },#{#[fg=#{@thm_subtle}]#S }}"
set -ga status-left "#[fg=brightblack]#S │"

# set -g status-left-length 100
# set -g status-left ""
# set -ga status-left "#{?#{!=:#{b:socket_path},default},  #{b:socket_path},}"
# set -ga status-left "#{?#{!=:#{b:socket_path},default}, #{#[fg=#{@thm_overlay}]│},}"
# set -ga status-left "#{?client_prefix,#{#[fg=#{@thm_text}]  },#{#[fg=#{@thm_subtle}]  }}"
# set -ga status-left "#{?client_prefix,#{#[fg=#{@thm_subtle}]#S },#{#[fg=#{@thm_subtle}]#S }}"
# set -ga status-left "#[fg=#{@thm_highlight_med}]│"

# window
set -gF window-status-separator " "
set -g window-status-format " #I#{?#{!=:#{window_name},Window},:#W,}"
set -g window-status-style "fg=brightblack"
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},:#W,}"
set -g window-status-current-style "fg=yellow"

# status right
set -g status-right-length 100
set -g status-right ""
set -ga status-right "#[fg=brightblack]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}} "
set -ga status-right "#[fg=brightblack]│"
set -ga status-right "#[fg=brightblack]  #{pane_current_command} "

# pane
set -wgF pane-active-border-style "fg=blue"
set -wgF pane-border-style "fg=black"

# popups
set -gF popup-style "bg=default,fg=white"
set -gF popup-border-style "fg=black"

# message
set -gF message-style "fg=green,bg=default"
set -gF message-command-style "fg=cyan,bg=default,align=centre"

# mode
set -gF mode-style "bg=black,bold"
