# term
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"
set -g extended-keys on
set -g extended-keys-format csi-u

# clipboard via OSC 52
set -s set-clipboard on

# vi mode
set -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection
bind-key -T copy-mode-vi Y send-keys -X copy-selection-and-cancel

# start windows and panes at 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# sensible defaults
set -g history-limit 100000
set -g focus-events on
set -s escape-time 0
set -g mouse on

# last window
bind b last-window
bind C-b last-window

# vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# seamless nvim/tmux pane nav
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?n?vim?$'"
bind -n M-h if-shell "$is_vim" "send-keys M-h" "select-pane -L"
bind -n M-j if-shell "$is_vim" "send-keys M-j" "select-pane -D"
bind -n M-k if-shell "$is_vim" "send-keys M-k" "select-pane -U"
bind -n M-l if-shell "$is_vim" "send-keys M-l" "select-pane -R"

# choose tree format
bind-key s choose-tree -s \
    -K "#{?#{e|<:#{line},19},#{a:#{e|+:72,#{line}}},}" \
    -F "#{?pane_format,#{?pane_marked,#[reverse],}#{pane_current_command}#{?pane_active,*,}#{?pane_marked,M,}#{?#{&&:#{pane_title},#{!=:#{pane_title},#{host_short}}},: \"#{pane_title}\",},#{?window_format,#{?window_marked_flag,#[reverse],}#{window_name}#{window_flags},#{?session_attached,#[fg=blue]*,}}}"

# pane keybindings
bind \" split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message " Config reloaded ✓"

# kill server
bind K confirm-before -p "kill server? (y/n)" kill-server

# colors
run-shell "~/.config/tc/tmux-load.sh"

# theme
source-file ~/.config/tmux/theme.conf
