# start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# set term as 256color
set -g default-terminal "xterm-256color"

# reload config on ctrl-b r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "config reloaded"

# use vim style selection/copy & paste
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi 'Enter' send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
set -g status-keys vi
setw -g mode-keys vi

# change escape delay to avoid lag in vim
set -s escape-time 0

# increase scrollback buffer size
set -g history-limit 50000

# style status bar
set -g status-left ''
set -g status-right ' #S '
set -g status-style bg=default,fg=colour8,bold

setw -g window-status-format ' #I #W '
setw -g window-status-current-format ' #[fg=colour11]#I #[fg=colour7]#W '

