# Status Background
set -g status-style "bg=default"

# Status Left
set -g status-left-length 100
set -g status-left " #{?client_prefix,#[fg=#{@thm_muted}] ,#[fg=#{@thm_highlight_high}] }"
set -ga status-left "#[fg=#{@thm_highlight_high}]#S #[fg=#{@thm_highlight_low}]│"

# Window
set -gF window-status-separator " #[fg=#{@thm_highlight_low}]│"
set -g window-status-format " #I#{?#{!=:#{window_name},Window},:#W,}"
set -g window-status-style "fg=#{@thm_highlight_high}"
set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},:#W,}"
set -g window-status-current-style "fg=#{@thm_rose}"

# Status Right
set -g status-right-length 100
set -g status-right "#{?#{!=:#{b:socket_path},default}, #[fg=#{@thm_highlight_high}] #{b:socket_path},}"
set -ga status-right "#{?#{!=:#{b:socket_path},default}, #[fg=#{@thm_highlight_low}]│,}"
set -ga status-right "#[fg=#{@thm_highlight_high}]  #{=/-32/...:#{s|$USER|~|:#{b:pane_current_path}}}"
set -ga status-right "#[fg=#{@thm_highlight_low}] │ #[fg=#{@thm_highlight_high}]"
set -ga status-right "#(gitmux -cfg $HOME/.config/gitmux/gitmux.conf \"#{pane_current_path}\") "

# Pane
set -wgF pane-active-border-style "fg=#{@thm_iris}"
set -wgF pane-border-style "fg=#{@thm_overlay}"

# Popups
set -gF popup-style "bg=default,fg=#{@thm_text}"
set -gF popup-border-style "fg=#{@thm_gold}"

# Message
set -gF message-style "fg=#{@thm_pine}"
set -gF message-command-style "fg=#{@thm_pine}"

# Mode
set -gF mode-style "bg=#{@thm_highlight_high},bold"
